version: '3.5'

services:
  pypiserver:
    image: pypiserver/pypiserver:latest
    container_name: pypiserver
    restart: always
    volumes:
      - ./microlibs:/data/packages
    ports:
      - "8080:8080"
  baz:
    image: baz
    build:
      context: applications/baz
      dockerfile: Dockerfile
      network: host
    container_name: baz
    volumes:
      - "./applications/baz:/app"
